---

- name: Configure master node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS="--node-ip={{ ansible_facts['eth1']['ipv4']['address'] }}"
    create: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address={{ ansible_facts['eth1']['ipv4']['address'] }} \
           --apiserver-cert-extra-sans={{ ansible_facts['eth1']['ipv4']['address'] }}  \
           --node-name {{ ansible_facts['nodename'] }} --pod-network-cidr=192.168.0.0/16

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
   - mkdir -p /home/vagrant/.kube
   - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
   - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Generate join command
  command: kubeadm token create --print-join-command
  force: yes
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
