---

- name: Copy the join command to server location
  copy: src=join-worker-command dest=/tmp/join-worker-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-worker-command.sh

- name: Flushing IP tables
  iptables:
    flush: yes